# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Rover' do

  use_frameworks!
  pod 'Firebase/Core', '5.0.0'
  pod 'Firebase/RemoteConfig', '5.0.0'

  target 'RoverTests' do
    inherit! :search_paths
    pod 'Nimble', '7.1.1'
  end

  target 'RoverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
