# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Rover' do

  use_frameworks!

  # Pods for Rover
  pod 'Firebase/Core'

  target 'RoverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
